export const LABELS = {
  ru: {
    eyebrow: 'GBWC',
    heroTitle: 'Партнёры',
    heroDesc: 'Совет взаимодействует с международными организациями, корпоративными партнёрами, государственными институтами и экспертными структурами.',
    intlTitle: 'Международные организации',
    intlDesc: 'Международные организации участвуют в пленарных заседаниях, инициативах и экспертных проектах GBWC.',
    corpTitle: 'Корпоративные партнёры',
    corpDesc: 'Корпоративные партнёры поддерживают инициативы Совета и участвуют в стратегическом диалоге.',
    natlTitle: 'Государственные партнёры',
    natlDesc: 'Государственные институты Казахстана участвуют в реализации инициатив и развитии международного сотрудничества.',
    instTitle: 'Институциональные партнёры',
    instDesc: 'Экспертные и образовательные организации, содействующие реализации инициатив Совета.',
    repLabel: 'Представитель',
    sessionLabel: 'Пленарные заседания',
    filterAll: 'Все',
    filterIntl: 'Международные',
    filterCorp: 'Корпоративные',
    filterNatl: 'Государственные',
    filterInst: 'Институциональные',
    coopLabel: 'ФОРМАТЫ СОТРУДНИЧЕСТВА',
    coopTitle: 'Партнёрство',
    coopItems: [
      { title: 'Участие в пленарных заседаниях', desc: 'Представители организаций участвуют в международных пленарных заседаниях GBWC в формате выступлений и дискуссий.' },
      { title: 'Совместные инициативы', desc: 'Реализация совместных проектов в области предпринимательства, образования, социальной политики и культуры.' },
      { title: 'Образовательные программы', desc: 'Сотрудничество в разработке и реализации образовательных программ, включая G-Index Academy и IT-AIEL.' },
      { title: 'Меморандумы о сотрудничестве', desc: 'Подписание официальных меморандумов о взаимодействии по ключевым направлениям деятельности Совета.' },
    ],
    ctaTitle: 'Стать партнёром',
    ctaText: 'Global Businesswomen Council открыт для новых партнёрств с международными организациями, государственными институтами и бизнес-сообществом.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Связаться',
  },
  en: {
    eyebrow: 'GBWC',
    heroTitle: 'Partners',
    heroDesc: 'The Council engages with international organisations, corporate partners, government institutions and expert structures.',
    intlTitle: 'International Organisations',
    intlDesc: 'International organisations participate in GBWC plenary sessions, initiatives and expert projects.',
    corpTitle: 'Corporate Partners',
    corpDesc: 'Corporate partners support Council initiatives and participate in strategic dialogue.',
    natlTitle: 'Government Partners',
    natlDesc: 'Kazakhstan government institutions participate in implementing initiatives and international cooperation.',
    instTitle: 'Institutional Partners',
    instDesc: 'Expert and educational organisations that support Council initiatives.',
    repLabel: 'Representative',
    sessionLabel: 'Plenary Sessions',
    filterAll: 'All',
    filterIntl: 'International',
    filterCorp: 'Corporate',
    filterNatl: 'Government',
    filterInst: 'Institutional',
    coopLabel: 'COOPERATION FORMATS',
    coopTitle: 'Partnership',
    coopItems: [
      { title: 'Plenary Session Participation', desc: 'Organisation representatives participate in GBWC international plenary sessions as speakers and discussants.' },
      { title: 'Joint Initiatives', desc: 'Joint project implementation in entrepreneurship, education, social policy and culture.' },
      { title: 'Educational Programmes', desc: 'Cooperation in developing educational programmes including G-Index Academy.' },
      { title: 'Memoranda of Understanding', desc: 'Signing official MoUs on cooperation across key Council activity areas.' },
    ],
    ctaTitle: 'Become a Partner',
    ctaText: 'Global Businesswomen Council is open to new partnerships with international organisations, government institutions and the business community.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Contact Us',
  },
  kk: {
    eyebrow: 'GBWC',
    heroTitle: 'Серіктестер',
    heroDesc: 'Кеңес халықаралық ұйымдармен, корпоративтік серіктестермен, мемлекеттік институттармен және сараптамалық құрылымдармен өзара іс-қимыл жасайды.',
    intlTitle: 'Халықаралық ұйымдар',
    intlDesc: 'Халықаралық ұйымдар GBWC пленарлық отырыстарына, бастамалар мен сараптамалық жобаларға қатысады.',
    corpTitle: 'Корпоративтік серіктестер',
    corpDesc: 'Корпоративтік серіктестер кеңес бастамаларын қолдайды және стратегиялық диалогқа қатысады.',
    natlTitle: 'Мемлекеттік серіктестер',
    natlDesc: 'Қазақстанның мемлекеттік институттары бастамаларды жүзеге асыруға және халықаралық ынтымақтастықты дамытуға қатысады.',
    instTitle: 'Институционалдық серіктестер',
    instDesc: 'Кеңес бастамаларын қолдайтын сараптамалық және білім беру ұйымдары.',
    repLabel: 'Өкіл',
    sessionLabel: 'Пленарлық отырыстар',
    filterAll: 'Барлығы',
    filterIntl: 'Халықаралық',
    filterCorp: 'Корпоративтік',
    filterNatl: 'Мемлекеттік',
    filterInst: 'Институционалдық',
    coopLabel: 'ЫНТЫМАҚТАСТЫҚ ФОРМАТТАРЫ',
    coopTitle: 'Серіктестік',
    coopItems: [
      { title: 'Пленарлық отырыстарға қатысу', desc: 'Ұйым өкілдері GBWC халықаралық пленарлық отырыстарына баяндамашылар мен талқылаушылар ретінде қатысады.' },
      { title: 'Бірлескен бастамалар', desc: 'Кәсіпкерлік, білім, әлеуметтік саясат және мәдениет саласындағы бірлескен жобаларды жүзеге асыру.' },
      { title: 'Білім беру бағдарламалары', desc: 'G-Index Academy мен IT-AIEL бағдарламаларын әзірлеуде ынтымақтастық.' },
      { title: 'Ынтымақтастық меморандумдары', desc: 'Кеңес қызметінің негізгі бағыттары бойынша ынтымақтастық туралы меморандумдарға қол қою.' },
    ],
    ctaTitle: 'Серіктес болу',
    ctaText: 'Global Businesswomen Council халықаралық ұйымдармен, мемлекеттік институттармен және іскерлік қауымдастықпен жаңа серіктестіктерге ашық.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Хабарласу',
  },
}
