/**
 * entities/initiatives/initiatives.data.js
 * All initiatives content.
 */
export const INITIATIVES_CONTENT = {
  ru: {
    eyebrow: 'GBWC',
    heroTitle: 'Инициативы',
    heroDesc: 'Совет реализует инициативы в области аналитики, образования, цифровых навыков, социальной поддержки и культурного сотрудничества.',
    intro: 'Global Businesswomen Council реализует инициативы, направленные на развитие предпринимательства, образовательных программ, социальных проектов и международного культурного сотрудничества. Инициативы реализуются в сотрудничестве с государственными институтами, международными организациями и деловым сообществом.',
    items: [
      {
        id: 'gindex',
        tag: 'АНАЛИТИКА & ИНСТИТУТ',
        num: '01',
        title: 'G-Index Initiative',
        desc: 'G-Index является институциональной инициативой Глобального совета женщин бизнеса, направленной на развитие аналитических инструментов и программ поддержки предпринимательства. Инициатива предусматривает развитие экспертного диалога, аналитических механизмов и образовательных программ, способствующих расширению экономических возможностей.',
        details: 'В рамках инициативы формируется комплексная система поддержки и развития предпринимательских инициатив, включающая аналитические, образовательные и институциональные механизмы. Инициатива реализуется во взаимодействии с международными организациями, государственными институтами, финансовыми структурами и экспертным сообществом.',
        tasks: [
          'Развитие аналитических инструментов оценки',
          'Формирование экспертных рекомендаций',
          'Поддержка международного экспертного диалога',
          'Разработка программ поддержки предпринимательства',
          'Взаимодействие с международными финансовыми институтами',
        ],
        image: null,
      },
      {
        id: 'hub',
        tag: 'ИНФРАСТРУКТУРА',
        num: '02',
        title: 'G-Index Hub',
        desc: 'G-Index Hub является институциональным центром реализации инициативы G-Index. Hub выполняет функции аналитического, экспертного и координационного центра, обеспечивающего развитие инициативы и взаимодействие с партнёрами.',
        details: 'Hub объединяет экспертов, представителей государственных институтов, международных организаций и делового сообщества. Платформа hub.gbwc.org обеспечивает цифровую инфраструктуру для сертификации, обучения, реестра предпринимателей и доступа корпоративных партнёров.',
        tasks: [
          'Развитие аналитических инструментов и методологий',
          'Подготовка экспертных рекомендаций и аналитических материалов',
          'Координация международного сотрудничества',
          'Сопровождение инициатив и проектов',
          'Цифровая инфраструктура: сертификация, реестр, академия',
        ],
        image: null,
      },
      {
        id: 'academy',
        tag: 'ОБРАЗОВАНИЕ',
        num: '03',
        title: 'G-Index Academy',
        desc: 'G-Index Academy является образовательным направлением инициативы G-Index. Академия реализует программы профессионального развития, направленные на развитие предпринимательских, управленческих и цифровых компетенций.',
        details: 'Образовательные программы Академии ориентированы на развитие профессиональных навыков, обмен опытом и формирование международных профессиональных связей. Академия объединяет экспертов, преподавателей, предпринимателей и представителей международных организаций для обмена знаниями и опытом.',
        tasks: [
          'Образовательные программы для предпринимателей',
          'Развитие управленческих и лидерских компетенций',
          'Наставнические программы и обмен опытом',
          'Международные образовательные партнёрства',
          'Развитие цифровых и технологических навыков',
        ],
        image: null,
      },
      {
        id: 'social',
        tag: 'СОЦИАЛЬНЫЕ ПРОЕКТЫ',
        num: '05',
        title: 'Центры поддержки семьи',
        desc: 'Пилотный проект создания центров поддержки семьи реализуется в регионах Казахстана совместно с Национальной комиссией по делам женщин, при консультативной поддержке Глобального института зеленого роста (GGGI).',
        details: 'Центры направлены на оказание комплексной помощи семьям в трудной жизненной ситуации: психологической, социальной, жилищной и юридической.',
        tasks: [
          'Психологическая помощь семьям',
          'Юридические консультации и правовая защита',
          'Социальная поддержка и сопровождение',
          'Жилищная помощь в кризисных ситуациях',
          'Координация с международными организациями',
        ],
        image: null,
      },
      {
        id: 'culture',
        tag: 'КУЛЬТУРНАЯ ДИПЛОМАТИЯ',
        num: '06',
        title: 'Культурные инициативы',
        desc: 'Глобальный совет участвует в проектах, направленных на позиционирование культурного ресурса как фактора устойчивого развития и укрепление международного диалога.',
        details: 'Особое внимание уделяется привлечению международного опыта в развитие культурных индустрий, а также формированию устойчивых механизмов взаимодействия в сфере креативной экономики и межкультурного обмена.',
        tasks: [
          'Международный культурный диалог',
          'Продвижение аутентичного наследия',
          'Развитие глобальной экспертизы',
          'Институциональное партнёрство',
        ],
        image: null,
      },
    ],
    partnershipLabel: 'ПАРТНЁРСТВО',
    partnershipTitle: 'Партнёрство в реализации инициатив',
    partnershipText: 'Инициативы Глобального совета женщин бизнеса реализуются в партнёрстве с международными организациями, государственными институтами, деловым сообществом и экспертными структурами. Совет выступает оператором и координатором проектов, обеспечивая взаимодействие между всеми участниками.',
    ctaTitle: 'Стать участником',
    ctaText: 'Совет открыт для сотрудничества с международными организациями, государственными институтами, образовательными учреждениями и бизнес-сообществом.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Написать нам',
    tasksLabel: 'Основные задачи',
  },
  en: {
    eyebrow: 'GBWC',
    heroTitle: 'Initiatives',
    heroDesc: 'The Council implements initiatives in analytics, education, digital skills, social support and cultural cooperation.',
    intro: 'Global Businesswomen Council implements initiatives aimed at entrepreneurship development, educational programmes, social projects and international cultural cooperation. Initiatives are implemented in cooperation with government institutions, international organisations and the business community.',
    items: [
      {
        id: 'gindex', tag: 'ANALYTICS & INSTITUTION', num: '01', title: 'G-Index Initiative',
        desc: 'G-Index is an institutional initiative of the Global Businesswomen Council aimed at developing analytical tools and entrepreneurship support programmes.',
        details: 'A comprehensive support system for entrepreneurial initiatives is being formed, including analytical, educational and institutional mechanisms, in interaction with international organisations, government institutions, financial structures and expert community.',
        tasks: ['Development of analytical assessment tools', 'Forming expert recommendations', 'Supporting international expert dialogue', 'Developing entrepreneurship support programmes', 'Engagement with international financial institutions'],
        image: null,
      },
      {
        id: 'hub', tag: 'INFRASTRUCTURE', num: '02', title: 'G-Index Hub',
        desc: 'G-Index Hub is the institutional centre for G-Index initiative implementation, performing analytical, expert and coordination functions.',
        details: 'The Hub brings together experts, government institutions, international organisations and the business community. The hub.gbwc.org platform provides digital infrastructure for certification, training, entrepreneur registry and corporate partner access.',
        tasks: ['Development of analytical tools and methodologies', 'Preparing expert recommendations', 'Coordinating international cooperation', 'Supporting initiatives and projects', 'Digital infrastructure: certification, registry, academy'],
        image: null,
      },
      {
        id: 'academy', tag: 'EDUCATION', num: '03', title: 'G-Index Academy',
        desc: 'G-Index Academy is the educational direction of the G-Index initiative, implementing professional development programmes for entrepreneurial, management and digital competencies.',
        details: 'Academy programmes focus on professional skill development, experience exchange and international professional networking. The Academy unites experts, educators, entrepreneurs and international organisation representatives.',
        tasks: ['Educational programmes for entrepreneurs', 'Management and leadership competencies development', 'Mentoring programmes and experience exchange', 'International educational partnerships', 'Digital and technology skills development'],
        image: null,
      },
      {
        id: 'social', tag: 'SOCIAL PROJECTS', num: '05', title: 'Family Support Centres',
        desc: 'The pilot Family Support Centres project is implemented in Kazakhstan regions together with the National Commission for Women\'s Affairs, with advisory support from the Global Green Growth Institute (GGGI).',
        details: 'The centres aim to provide comprehensive assistance to families in difficult situations: psychological, social, housing and legal support.',
        tasks: ['Psychological assistance to families', 'Legal consultations and protection', 'Social support and accompaniment', 'Housing assistance in crisis situations', 'Coordination with international organisations'],
        image: null,
      },
      {
        id: 'culture', tag: 'CULTURAL DIPLOMACY', num: '06', title: 'Cultural Initiatives',
        desc: 'The Global Council participates in projects aimed at positioning cultural resources as a factor of sustainable development and strengthening international dialogue.',
        details: 'Special attention is paid to attracting international expertise to cultural industries development, as well as forming sustainable interaction mechanisms in the creative economy and intercultural exchange.',
        tasks: ['International cultural dialogue', 'Promoting authentic heritage', 'Developing global expertise', 'Institutional partnership'],
        image: null,
      },
    ],
    partnershipLabel: 'PARTNERSHIP',
    partnershipTitle: 'Partnership in Implementing Initiatives',
    partnershipText: 'GBWC initiatives are implemented in partnership with international organisations, government institutions, the business community and expert structures. The Council acts as operator and coordinator of projects.',
    ctaTitle: 'Join Us',
    ctaText: 'The Council is open to cooperation with international organisations, government institutions, educational establishments and the business community.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Contact Us',
    tasksLabel: 'Key Tasks',
  },
  kk: {
    eyebrow: 'GBWC',
    heroTitle: 'Бастамалар',
    heroDesc: 'Кеңес аналитика, білім беру, цифрлық дағдылар, әлеуметтік қолдау және мәдени ынтымақтастық саласында бастамаларды жүзеге асырады.',
    intro: 'Global Businesswomen Council кәсіпкерлікті, білім беру бағдарламаларын, әлеуметтік жобаларды және халықаралық мәдени ынтымақтастықты дамытуға бағытталған бастамаларды жүзеге асырады.',
    items: [
      {
        id: 'gindex', tag: 'АНАЛИТИКА & ИНСТИТУТ', num: '01', title: 'G-Index Initiative',
        desc: 'G-Index — аналитикалық құралдарды дамытуға және кәсіпкерлікті қолдау бағдарламаларына бағытталған институционалдық бастама.',
        details: 'Бастама аналитикалық, білім беру және институционалдық тетіктерді қамтитын кәсіпкерлік бастамаларды қолдаудың кешенді жүйесін қалыптастырады.',
        tasks: ['Бағалаудың аналитикалық құралдарын дамыту', 'Сараптамалық ұсынымдар қалыптастыру', 'Халықаралық диалогты қолдау', 'Кәсіпкерлікті қолдау бағдарламаларын әзірлеу', 'Халықаралық қаржы институттарымен өзара іс-қимыл'],
        image: null,
      },
      {
        id: 'hub', tag: 'ИНФРАҚҰРЫЛЫМ', num: '02', title: 'G-Index Hub',
        desc: 'G-Index Hub — аналитикалық, сараптамалық және үйлестіру орталығы ретінде G-Index бастамасын жүзеге асырудың институционалдық орталығы.',
        details: 'Hub сарапшыларды, мемлекеттік институттар мен халықаралық ұйымдар өкілдерін біріктіреді. hub.gbwc.org платформасы сертификаттау, оқыту және кәсіпкерлер тізілімі үшін цифрлық инфрақұрылымды қамтамасыз етеді.',
        tasks: ['Аналитикалық құралдар мен әдістемелерді дамыту', 'Сараптамалық ұсынымдар дайындау', 'Халықаралық ынтымақтастықты үйлестіру', 'Бастамалар мен жобаларды сүйемелдеу', 'Цифрлық инфрақұрылым: сертификаттау, тізілім, академия'],
        image: null,
      },
      {
        id: 'academy', tag: 'БІЛІМ БЕРУ', num: '03', title: 'G-Index Academy',
        desc: 'G-Index Academy — G-Index бастамасының білім беру бағыты, кәсіпкерлік, басқарушылық және цифрлық дағдыларды дамытуға арналған кәсіби даму бағдарламаларын жүзеге асырады.',
        details: 'Академия бағдарламалары кәсіби дағдыларды дамытуға, тәжірибе алмасуға және халықаралық кәсіби байланыстарды қалыптастыруға бағытталған.',
        tasks: ['Кәсіпкерлерге арналған білім беру бағдарламалары', 'Басқарушылық және көшбасшылық дағдыларды дамыту', 'Тәлімгерлік бағдарламалары', 'Халықаралық білім беру серіктестіктері', 'Цифрлық дағдыларды дамыту'],
        image: null,
      },
      {
        id: 'social', tag: 'ӘЛЕУМЕТТІК ЖОБАЛАР', num: '05', title: 'Отбасын қолдау орталықтары',
        desc: 'Отбасын қолдау орталықтарының пилоттық жобасы Қазақстан өңірлерінде Әйелдер істері жөніндегі ұлттық комиссиямен бірлесіп, Жаһандық жасыл өсу институтының (GGGI) консультативтік қолдауымен жүзеге асырылуда.',
        details: 'Орталықтар қиын өмірлік жағдайға тап болған отбасыларға кешенді психологиялық, әлеуметтік, тұрғын үй және құқықтық көмек көрсетуге бағытталған.',
        tasks: ['Отбасыларға психологиялық көмек', 'Заңдық кеңестер мен қорғаныс', 'Әлеуметтік қолдау', 'Дағдарыстық жағдайда тұрғын үй көмегі', 'Халықаралық ұйымдармен үйлестіру'],
        image: null,
      },
      {
        id: 'culture', tag: 'МӘДЕНИ ДИПЛОМАТИЯ', num: '06', title: 'Мәдени бастамалар',
        desc: 'Жаһандық кеңес мәдени ресурсты тұрақты даму факторы ретінде көрсетуге және халықаралық диалогты нығайтуға бағытталған жобаларға қатысады.',
        details: 'Мәдени индустрияларды дамытуға халықаралық тәжірибені тартуға, сондай-ақ креативті экономика және мәдениетаралық алмасу саласындағы тұрақты өзара іс-қимыл тетіктерін қалыптастыруға ерекше назар аударылады.',
        tasks: ['Халықаралық мәдени диалог', 'Төл мұраны насихаттау', 'Жаһандық сараптаманы дамыту', 'Институционалдық серіктестік'],
        image: null,
      },
    ],
    partnershipLabel: 'СЕРІКТЕСТІК',
    partnershipTitle: 'Бастамаларды жүзеге асырудағы серіктестік',
    partnershipText: 'GBWC бастамалары халықаралық ұйымдармен, мемлекеттік институттармен, іскерлік қауымдастықпен серіктестікте жүзеге асырылады.',
    ctaTitle: 'Серіктес болу',
    ctaText: 'Кеңес халықаралық ұйымдармен, мемлекеттік институттармен, білім беру мекемелерімен ынтымақтасуға ашық.',
    ctaEmail: 'partnerships@gbwc.org',
    ctaBtn: 'Хабарласу',
    tasksLabel: 'Негізгі міндеттер',
  },
}
