export const ARTICLES = [
  {
    id: 1,
    source: 'The Astana Times',
    category: 'international',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'Женщины в бизнесе подчеркнули силу инклюзивных социальных инвестиций в Астане',
      en: 'Women in Business Highlight Power of Inclusive Social Investment in Astana',
      kk: 'Астанадағы іскер әйелдер инклюзивті әлеуметтік инвестициялардың күшін атап өтті',
    },
    url: 'https://astanatimes.com/2025/06/women-in-business-highlight-power-of-inclusive-social-investment-in-astana/',
    image: 'https://astanatimes.com/wp-content/uploads/2025/06/image-11-scaled.jpeg',
  },
  {
    id: 2,
    source: 'Silkway TV',
    category: 'national',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'В Астане прошло заседание женщин-лидеров Global Businesswomen Council',
      en: 'Global Businesswomen Council Meeting of Women Leaders Held in Astana',
      kk: 'Астанада Global Businesswomen Council әйел-көшбасшылар отырысы өтті',
    },
    url: 'https://silkwaytv.kz/ru/v-astane-proshlo-zasedanie-zhenshchin-liderov-gbwc_56404',
  },
  {
    id: 3,
    source: '24KZ',
    category: 'national',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'Роль женщин в формировании устойчивой глобальной повестки обсудили в Астане',
      en: 'Role of Women in Shaping a Sustainable Global Agenda Discussed in Astana',
      kk: 'Астанада әйелдердің тұрақты жаһандық күн тәртібін қалыптастырудағы рөлі талқыланды',
    },
    url: 'https://24.kz/amp/ru/news/social/716846-rol-zhenshchin-v-formirovanii-ustojchivoj-globalnoj-povestki-obsudili-v-astane',
  },
  {
    id: 4,
    source: '365info',
    category: 'national',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'Женщины-лидеры обсудили развитие социальных инвестиций в Казахстане',
      en: 'Women Leaders Discuss Development of Social Investments in Kazakhstan',
      kk: 'Әйел-көшбасшылар Қазақстандағы әлеуметтік инвестициялардың дамуын талқылады',
    },
    url: 'https://365info.kz/2025/06/zhenshhiny-lidery-obsudili-razvitie-sotsialnyh-investitsii-y-kazahstane',
  },
  {
    id: 5,
    source: 'Inform.kz',
    category: 'national',
    date: { ru: 'Июнь 2023', en: 'June 2023', kk: '2023 маусым' },
    title: {
      ru: 'Новые возможности в бизнесе для женщин обсудили в Астане',
      en: 'New Business Opportunities for Women Discussed in Astana',
      kk: 'Астанада әйелдерге арналған жаңа бизнес мүмкіндіктері талқыланды',
    },
    url: 'https://www.inform.kz/ru/novye-vmozhnosti-v-biznese-dlya-zhenschin-obsudili-v-astane_a4076242',
  },
  {
    id: 6,
    source: 'BaigeNews',
    category: 'national',
    date: { ru: 'Июнь 2023', en: 'June 2023', kk: '2023 маусым' },
    title: {
      ru: 'Новые возможности женщин в бизнесе обсудили в Астане',
      en: 'New Opportunities for Women in Business Discussed in Astana',
      kk: 'Астанада бизнестегі әйелдердің жаңа мүмкіндіктері талқыланды',
    },
    url: 'https://baigenews.kz/novye-vmozhnosti-zhenschin-v-biznese-obsudili-v-astane_154200/',
  },
  {
    id: 7,
    source: 'Jas.kz',
    category: 'kazakh',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'На заседании Global Businesswomen Council женщины-лидеры обсудили вопросы социальных инвестиций',
      en: 'At the Global Businesswomen Council meeting women leaders discussed social investment issues',
      kk: 'Global Businesswomen Council отырысында әйелдер-көшбасшылар әлеуметтік инвестициялар мәселесін талқылады',
    },
    url: 'https://jas.kz/25-06-2025/global-businesswomen-council-отырысында-әйелдер-көшбасшылар/?amp=1',
  },
  {
    id: 8,
    source: 'Jarialke.kz',
    category: 'kazakh',
    date: { ru: 'Июнь 2025', en: 'June 2025', kk: '2025 маусым' },
    title: {
      ru: 'Во Дворце Независимости в Астане прошло заседание Global Businesswomen Council',
      en: 'Global Businesswomen Council Meeting Held at the Palace of Independence in Astana',
      kk: 'Астанадағы Тәуелсіздік сарайында Global Businesswomen Council (GBWC) жиыны өтті',
    },
    url: 'https://jarialke.kz/734/astanada-y-t-ulesizdik-sarayynda-global-business-women-council-gbwc-zhyny-tti',
  },
]
