/**
 * entities/about/about.data.js
 * About page multilingual content — entity layer, single source of truth.
 */
export const ABOUT_CONTENT = {
  ru: {
    heroEye: 'GBWC', heroTitle: 'О Совете',
    heroDesc: 'Global Businesswomen Council — международный совет, содействующий развитию сотрудничества между государственными институтами, международными организациями и деловым сообществом.',
    stats: [
      { n: '2023', l: 'Год основания' }, { n: '3', l: 'Пленарных заседания' },
      { n: '13+', l: 'Стран-участниц' }, { n: '15+', l: 'Партнёров' },
    ],
    mandateEye: 'О СОВЕТЕ', mandateTitle: 'Институциональный мандат',
    mandateParas: [
      'GBWC осуществляет деятельность по развитию международного сотрудничества в предпринимательстве, социальной политике, образовании и культурном взаимодействии.',
      'Совет объединяет государственные институты, международные организации и деловое сообщество для обсуждения актуальных вопросов экономического развития.',
      'Деятельность направлена на развитие международного диалога и расширение экономических возможностей.',
      'Совет взаимодействует с государственными органами, международными финансовыми институтами и представителями бизнеса.',
    ],
    asideCards: [
      { label: 'Год основания', num: '2023', sub: 'Международный совет' },
    ],
    dirEye: 'ДЕЯТЕЛЬНОСТЬ', dirTitle: 'Направления',
    dirs: [
      { n: '01', title: 'Международное сотрудничество и дипломатия', desc: 'Развитие взаимодействия с международными организациями. Совет объединяет участников из 13+ стран.' },
      { n: '02', title: 'Развитие женского предпринимательства', desc: 'Реализация программ G-Index Initiative, G-Index Academy.' },
      { n: '03', title: 'Социальные инвестиции и партнерства', desc: 'Пилотный проект «Центр поддержки семьи» совместно с GGGI в регионах Казахстана.' },
      { n: '04', title: 'Культурное взаимодействие', desc: 'Укрепление международного диалога и продвижение наследия на международном уровне.' },
    ],
    timelineEye: 'ИСТОРИЯ', timelineTitle: 'Хронология',
    timeline: [
      { year: '2023', title: 'Основание Совета', desc: '7 июня 2023 — I Пленарное заседание в рамках 35-го заседания СИИ при Президенте РК. 22 участника из числа руководителей глобальных организаций.' },
      { year: '2024', title: 'Расширение деятельности', desc: '31 октября 2024 — II Пленарное заседание во Дворце Независимости.' },
      { year: '2025', title: 'Международное признание', desc: '24 июня 2025 — III Пленарное заседание. Подписаны меморандумы с тремя министерствами. Хор КазНУИ выступил в Ватикане.' },
      { year: '2026', title: 'Стратегическое развитие', desc: 'Развитие G-Index Hub. Реализация партнёрских проектов. Подготовка IV Пленарного заседания.' },
    ],
    princEye: 'ПРИНЦИПЫ', princTitle: 'Основы деятельности',
    princs: [
      { n: '1', title: 'Международное сотрудничество', desc: 'Устойчивые механизмы взаимодействия между государственными структурами и деловым сообществом.' },
      { n: '2', title: 'Институциональное партнёрство', desc: 'Сотрудничество с ведущими международными организациями на равноправной основе.' },
      { n: '3', title: 'Открытый диалог', desc: 'Свободный обмен мнениями между участниками из различных стран.' },
      { n: '4', title: 'Развитие предпринимательства', desc: 'Поддержка инициатив по расширению экономических возможностей.' },
      { n: '5', title: 'Социальная ответственность', desc: 'Содействие проектам по повышению качества жизни и поддержке семей.' },
    ],
    founderEye: 'ОСНОВАТЕЛЬ',
    founderPhoto: '/img/founders/zhanna_baidasheva.jpeg', founderTitle: 'Жанна Амановна Байдашева',
    founderRole: 'Основатель Global Businesswomen Council',
    founderBio: [
      'Эксперт в области международной экономики и инвестиционной политики с более чем 20-летним управленческим опытом. Выпускница РФМШ и программы «Болашак» со степенью магистра Queen Mary University of London (Инвестиции и финансы).',
      'Профессиональный путь Жанны включает стратегическую работу в Азиатском Банке Развития (ЦАРЭС) и Евразийском банке развития, а также ключевые позиции в государственном аппарате — от советника Министра экономики до инспектора Администрации Президента РК.',
      'С 2012 года возглавляет Ассоциацию «Казахстанский Совет иностранных инвесторов» при Президенте РК, координируя диалог между государством и глобальным бизнесом. В 2022 году основала GBWC для продвижения интересов женщин-предпринимателей на международном уровне.',
      'В 2025 году по решению Главы государства вошла в состав Национальной комиссии по делам женщин и демографической политике. Также является членом Общественного совета при Министерстве науки и высшего образования РК, активно содействуя развитию научного потенциала и образовательных инициатив в Казахстане.',
    ],
    founderPoints: [],
    secretEye: 'СЕКРЕТАРИАТ', secretTitle: 'Команда',
    team: [
      { name: 'Бибигуль Аманбаевна Масербаева', role: 'Руководитель Секретариата', email: 'bibigul.maserbaeva@gbwc.network', points: ['Организационная координация', 'Подготовка международных мероприятий', 'Взаимодействие с институтами', 'Сопровождение инициатив'] },
      { name: 'Сана Кумаргазы', role: 'Ассистент Секретариата', email: 'sana.kumargazy@gbwc.network', points: ['Организационная поддержка', 'Подготовка мероприятий', 'Работа с партнёрами', 'Сопровождение проектов'] },
    ],
    mvvEye: 'МИССИЯ',
    mission: 'Миссия GBWC — содействие развитию международного сотрудничества и укреплению взаимодействия между государственными институтами, международными организациями и деловым сообществом.',
    vision: 'Совет развивает устойчивые механизмы международного взаимодействия, способствующие расширению предпринимательских возможностей по всему миру.',
    values: [
      { title: 'Международное сотрудничество', desc: 'Взаимодействие государственных институтов и делового сообщества.' },
      { title: 'Институциональное партнёрство', desc: 'Сотрудничество с ведущими международными структурами.' },
      { title: 'Открытый диалог', desc: 'Обмен опытом между участниками разных стран.' },
      { title: 'Развитие предпринимательства', desc: 'Расширение экономических возможностей.' },
      { title: 'Социальная ответственность', desc: 'Повышение качества жизни и поддержка семей.' },
    ],
    ctaText: 'Совет открыт для сотрудничества с международными организациями, государственными институтами и бизнес-сообществом.',
    ctaInit: 'Инициативы', ctaPart: 'Партнёры',
  },
  en: {
    heroEye: 'GBWC', heroTitle: 'About',
    heroDesc: 'Global Businesswomen Council is an international council promoting cooperation between government institutions, international organisations and the business community.',
    stats: [{ n: '2023', l: 'Founded' }, { n: '3', l: 'Plenary Sessions' }, { n: '13+', l: 'Countries' }, { n: '15+', l: 'Partners' }],
    mandateEye: 'ABOUT', mandateTitle: 'Institutional Mandate',
    mandateParas: ['GBWC conducts activities to develop international cooperation in entrepreneurship, social policy, education and cultural interaction.', 'The Council brings together government institutions, international organisations and the business community to form joint initiatives.', 'Activities focus on developing international dialogue and expanding economic opportunities.', 'The Council works with government bodies, international financial institutions and business representatives.'],
    asideCards: [{ label: 'Founded', num: '2023', sub: 'International Council' }],
    dirEye: 'ACTIVITY', dirTitle: 'Focus Areas',
    dirs: [{ n: '01', title: 'International Cooperation and Diplomacy', desc: 'Developing interaction with international organisations. The Council unites participants from 13+ countries.' }, { n: '02', title: 'Women\'s Entrepreneurship Development', desc: 'Implementing G-Index Initiative, G-Index Academy programmes.' }, { n: '03', title: 'Social Investments and Partnerships', desc: 'GBWC operates pilot Family Support Centres in Kazakhstan regions.' }, { n: '04', title: 'Cultural Interaction', desc: 'Strengthening international cultural dialogue and diplomacy.' }],
    timelineEye: 'HISTORY', timelineTitle: 'Timeline',
    timeline: [{ year: '2023', title: 'Founding', desc: 'June 7, 2023 — 1st Plenary Session at the 35th FIC Plenary. 22 participants from global organisations.' }, { year: '2024', title: 'Expansion', desc: 'October 31, 2024 — 2nd Plenary Session.' }, { year: '2025', title: 'International Recognition', desc: 'June 24, 2025 — 3rd Plenary Session. MoUs with three Kazakhstan ministries. KazNUI choir at Vatican.' }, { year: '2026', title: 'Strategic Development', desc: 'G-Index Hub development. Partnership projects. Preparation for 4th Plenary Session.' }],
    princEye: 'PRINCIPLES', princTitle: 'Foundations',
    princs: [{ n: '1', title: 'International Cooperation', desc: 'Sustainable interaction between government structures and business community.' }, { n: '2', title: 'Institutional Partnership', desc: 'Cooperation with leading international organisations on equal terms.' }, { n: '3', title: 'Open Dialogue', desc: 'Free exchange of views between participants from different countries.' }, { n: '4', title: 'Entrepreneurship Development', desc: 'Supporting initiatives for economic opportunity expansion.' }, { n: '5', title: 'Social Responsibility', desc: 'Promoting projects for quality of life improvement.' }],
    founderEye: 'FOUNDER',
    founderPhoto: '/img/founders/zhanna_baidasheva.jpeg', founderTitle: 'Zhanna Amanovna Baidasheva',
    founderRole: 'Founder, Global Businesswomen Council',
    founderBio: ['Zhanna Baidasheva holds a BSc from al-Farabi KazNU and an MSc from Queen Mary University of London (Bolashak Programme).', 'From 2004–2007, CAREC Coordinator at the Asian Development Bank. In 2007–2008, Senior Analyst at the Eurasian Development Bank.', 'From 2009–2011, Advisor to the Minister of Economy. In 2011–2012, Inspector at the Presidential Administration.', 'Since 2012, Director of the Kazakhstan Foreign Investors Council Association (AKSII). In 2023, founded GBWC.'],
    founderPoints: ['International economic cooperation development', 'Engagement with international financial institutions', 'Entrepreneurship and investment cooperation', 'Social and educational initiative support', 'Presidential Decree No. 893 (2025): appointed to National Commission on Women\'s Affairs'],
    secretEye: 'SECRETARIAT', secretTitle: 'Team',
    team: [{ name: 'Bibigul Amanbaevna Maserbaeva', role: 'Head of Secretariat', email: 'bibigul.maserbaeva@gbwc.network', points: ['Organisational coordination', 'International event preparation', 'Interaction with institutions', 'Initiative support'] }, { name: 'Sana Kumargazy', role: 'Secretariat Assistant', email: 'sana.kumargazy@gbwc.network', points: ['Organisational support', 'Event preparation', 'Partner coordination', 'Project support'] }],
    mvvEye: 'MISSION',
    mission: 'The mission of GBWC is to promote international cooperation and strengthen interaction between government institutions, international organisations and the business community.',
    vision: 'The Council develops sustainable international interaction mechanisms that expand entrepreneurial opportunities worldwide.',
    values: [{ title: 'International Cooperation', desc: 'Interaction between government institutions and business community.' }, { title: 'Institutional Partnership', desc: 'Cooperation with leading international structures.' }, { title: 'Open Dialogue', desc: 'Experience exchange between participants.' }, { title: 'Entrepreneurship Development', desc: 'Expanding economic opportunities.' }, { title: 'Social Responsibility', desc: 'Quality of life improvement and family support.' }],
    ctaText: 'The Council is open to cooperation with international organisations, government institutions and the business community.',
    ctaInit: 'Initiatives', ctaPart: 'Partners',
  },
  kk: {
    heroEye: 'GBWC', heroTitle: 'Кеңес туралы',
    heroDesc: 'Global Businesswomen Council — мемлекеттік институттар, халықаралық ұйымдар мен іскерлік қауымдастық арасындағы ынтымақтастықты дамытатын халықаралық кеңес.',
    stats: [{ n: '2023', l: 'Құрылған жыл' }, { n: '3', l: 'Пленарлық отырыс' }, { n: '13+', l: 'Елдер' }, { n: '15+', l: 'Серіктестер' }],
    mandateEye: 'КЕҢЕС ТУРАЛЫ', mandateTitle: 'Институциональды мандат',
    mandateParas: ['GBWC кәсіпкерлік, әлеуметтік саясат, білім беру саласындағы халықаралық ынтымақтастықты дамытуға бағытталған қызметті жүзеге асырады.', 'Кеңес мемлекеттік институттар мен іскерлік қауымдастық өкілдерін бірлескен бастамалар қалыптастыру үшін біріктіреді.', 'Кеңестің қызметі халықаралық диалогты дамытуға және экономикалық мүмкіндіктерді кеңейтуге бағытталған.', 'Кеңес мемлекеттік органдармен, халықаралық қаржы институттарымен және бизнес өкілдерімен өзара іс-қимыл жасайды.'],
    asideCards: [{ label: 'Құрылған жылы', num: '2023', sub: 'Халықаралық кеңес' }],
    dirEye: 'ҚЫЗМЕТ', dirTitle: 'Бағыттар',
    dirs: [{ n: '01', title: 'Халықаралық ынтымақтастық және дипломатия', desc: '13+ елден қатысушыларды біріктіреді.' }, { n: '02', title: 'Әйелдер кәсіпкерлігін дамыту', desc: 'G-Index Initiative, G-Index Academy бағдарламалары.' }, { n: '03', title: 'Әлеуметтік инвестициялар және серіктестік', desc: 'Отбасын қолдау орталықтарының пилоттық жобасы.' }, { n: '04', title: 'Мәдени өзара іс-қимыл', desc: 'Халықаралық диалогты нығайту және мұраны жаһандық деңгейде ілгерілету.' }],
    timelineEye: 'ТАРИХ', timelineTitle: 'Хронология',
    timeline: [{ year: '2023', title: 'Кеңестің құрылуы', desc: '2023 жылы 7 маусымда I Пленарлық отырыс өтті.' }, { year: '2024', title: 'Қызметті кеңейту', desc: 'II Пленарлық отырыс.' }, { year: '2025', title: 'Халықаралық тану', desc: 'III Пленарлық отырыс. Меморандумдарға қол қойылды.' }, { year: '2026', title: 'Стратегиялық даму', desc: 'G-Index Hub. IV Пленарлық отырысқа дайындық.' }],
    princEye: 'ҚАҒИДАТТАР', princTitle: 'Негіздер',
    princs: [{ n: '1', title: 'Халықаралық ынтымақтастық', desc: 'Тұрақты өзара іс-қимыл механизмдерін дамыту.' }, { n: '2', title: 'Институциональды серіктестік', desc: 'Халықаралық ұйымдармен теңдік негізінде ынтымақтасу.' }, { n: '3', title: 'Ашық диалог', desc: 'Қатысушылар арасында пікір алмасу.' }, { n: '4', title: 'Кәсіпкерлікті дамыту', desc: 'Экономикалық мүмкіндіктерді кеңейту.' }, { n: '5', title: 'Әлеуметтік жауапкершілік', desc: 'Өмір сапасын арттыру жобаларын жеделдету.' }],
    founderEye: 'НЕГІЗІН ҚАЛАУШЫ',
    founderPhoto: '/img/founders/zhanna_baidasheva.jpeg', founderTitle: 'Жанна Амановна Байдашева',
    founderRole: 'Global Businesswomen Council негізін қалаушы',
    founderBio: ['Жанна Байдашева ҚазҰУ экономикалық кибернетика бакалавры және Лондон Queen Mary университетінің инвестиция магистрі.', '2004–2007 жылдары АДБ-да ЦАРЭС координаторы. 2007–2008 — Еуразиялық даму банкінің аналитигі.', '2009–2011 — ҚР Экономика министрінің Кеңесшісі. 2011–2012 — ҚР Президенті Әкімшілігінде инспектор.', '2012 жылдан ҚШИК Ассоциациясының директоры. 2023 жылы GBWC-ты құрды.'],
    founderPoints: ['Халықаралық экономикалық ынтымақтастықты дамыту', 'Халықаралық қаржы институттарымен өзара іс-қимыл', 'Кәсіпкерлікті дамыту', 'Әлеуметтік бастамаларды қолдау', 'Президент жарлығы №893 (2025): Ұлттық комиссия мүшесі'],
    secretEye: 'ХАТШЫЛЫҚ', secretTitle: 'Команда',
    team: [{ name: 'Бибігүл Аманбайқызы Масербаева', role: 'Хатшылық жетекшісі', email: 'bibigul.maserbaeva@gbwc.network', points: ['Ұйымдастырушылық үйлестіру', 'Іс-шараларды дайындау', 'Институттармен өзара іс-қимыл', 'Бастамаларды қолдау'] }, { name: 'Сана Кумаргазы', role: 'Хатшылық ассистенті', email: 'sana.kumargazy@gbwc.network', points: ['Ұйымдастырушылық қолдау', 'Іс-шараларды дайындау', 'Серіктестермен үйлестіру', 'Жобаларды қолдау'] }],
    mvvEye: 'МИССИЯ',
    mission: 'GBWC миссиясы — мемлекеттік институттар, халықаралық ұйымдар мен іскерлік қауымдастық арасындағы ынтымақтастықтың дамуына жәрдемдесу.',
    vision: 'Кеңес кәсіпкерлік мүмкіндіктерді кеңейтуге ықпал ететін тұрақты халықаралық өзара іс-қимыл механизмдерін дамытады.',
    values: [{ title: 'Халықаралық ынтымақтастық', desc: 'Мемлекеттік институттар мен іскерлік қауымдастық арасындағы өзара іс-қимыл.' }, { title: 'Институциональды серіктестік', desc: 'Халықаралық құрылымдармен ынтымақтасу.' }, { title: 'Ашық диалог', desc: 'Тәжірибе алмасу.' }, { title: 'Кәсіпкерлікті дамыту', desc: 'Экономикалық мүмкіндіктерді кеңейту.' }, { title: 'Әлеуметтік жауапкершілік', desc: 'Өмір сапасын арттыру.' }],
    ctaText: 'Кеңес халықаралық ұйымдармен және іскерлік қауымдастықпен ынтымақтасуға ашық.',
    ctaInit: 'Бастамалар', ctaPart: 'Серіктестер',
  },
}
