/**
 * entities/partners/partners.data.js
 * All partner logos are inline SVG data URIs — guaranteed to load, no external CDN.
 */
import { PARTNER_LOGOS as L } from './partner_logos.js'

/** Build public photo URL for a partner representative photo */
const P = (filename) => `/img/partners/${filename}`

export const PARTNERS = {
  intl: [
    { name: 'EBRD',      logo: L.EBRD, url: 'https://www.ebrd.com',         full: { ru: 'Европейский банк реконструкции и развития', en: 'European Bank for Reconstruction and Development', kk: 'Еуропалық қайта жаңарту және даму банкі' }, rep: { ru: 'Одиль Рено-Бассо, Президент', en: 'Odile Renaud-Basso, President', kk: 'Одиль Рено-Бассо, Президент' }, photo: P('Одиль Рено-Бассо.jpg'), sessions: [1,2,3] },
    { name: 'World Bank', logo: L.WorldBank, url: 'https://www.worldbank.org',    full: { ru: 'Всемирный Банк', en: 'World Bank', kk: 'Дүниежүзілік банк' }, rep: { ru: 'Антонелла Бассани, Вице-президент', en: 'Antonella Bassani, VP Europe & CA', kk: 'Антонелла Бассани, VP' }, photo: P('Антонелла Бассани.jpeg'), sessions: [1] },
    { name: 'UNDP',       logo: L.UNDP, url: 'https://www.undp.org',         full: { ru: 'Программа развития ООН', en: 'United Nations Development Programme', kk: 'БҰҰ Даму бағдарламасы' }, rep: { ru: 'Катаржина Вавьерниа, Постоянный представитель в РК', en: 'Katarzyna Wawiernia, Resident Representative', kk: 'Катаржина Вавьерниа, тұрақты өкіл' }, photo: P('Катаржина Вавьерниа.jpg'), sessions: [2] },
    { name: 'ADB',        logo: L.ADB, url: 'https://www.adb.org',          full: { ru: 'Азиатский банк развития', en: 'Asian Development Bank', kk: 'Азия даму банкі' }, rep: null, photo: null, sessions: [] },
    { name: 'IFC',        logo: L.IFC, url: 'https://www.ifc.org',          full: { ru: 'Международная финансовая корпорация', en: 'International Finance Corporation', kk: 'Халықаралық қаржы корпорациясы' }, rep: null, photo: null, sessions: [] },
    { name: 'IsDB',       logo: L.IsDB, url: 'https://www.isdb.org',         full: { ru: 'Исламский банк развития', en: 'Islamic Development Bank', kk: 'Ислам даму банкі' }, rep: null, photo: null, sessions: [] },
    { name: 'GGGI',       logo: L.GGGI, url: 'https://gggi.org',         full: { ru: 'Глобальный институт зелёного роста', en: 'Global Green Growth Institute', kk: 'Жаһандық жасыл өсу институты' }, rep: null, photo: null, sessions: [] },
    { name: 'UN Women',   logo: L.UNWomen, url: 'https://www.unwomen.org',      full: { ru: 'ООН-Женщины', en: 'UN Women', kk: 'БҰҰ-Əйелдер' }, rep: null, photo: null, sessions: [] },
    { name: 'OSCE',       logo: L.OSCE, url: 'https://www.osce.org',         full: { ru: 'Организация по безопасности и сотрудничеству в Европе', en: 'Organisation for Security and Cooperation in Europe', kk: 'Еуропадағы қауіпсіздік және ынтымақтастық ұйымы' }, rep: { ru: 'Маргарета Седерфельт, Председатель ПА ОБСЕ', en: 'Margareta Cederfelt, President PA OSCE', kk: 'Маргарета Седерфельт, ЕҚЫҰ ПА Президенті' }, photo: null, sessions: [1] },
    { name: 'AIIB',       logo: L.AIIB, url: 'https://www.aiib.org',         full: { ru: 'Азиатский банк инфраструктурных инвестиций', en: 'Asian Infrastructure Investment Bank', kk: 'Азия инфрақұрылымдық инвестициялар банкі' }, rep: null, photo: null, sessions: [] },
    { name: 'ILO',        logo: L.ILO, url: 'https://www.ilo.org',          full: { ru: 'Международная организация труда', en: 'International Labour Organization', kk: 'Халықаралық еңбек ұйымы' }, rep: null, photo: null, sessions: [] },
  ],
  corp: [
    { name: 'Baker McKenzie', logo: L.BakerMcKenzie, url: 'https://www.bakermckenzie.com', full: { ru: 'Baker McKenzie International', en: 'Baker McKenzie International', kk: 'Baker McKenzie International' }, rep: { ru: 'Кирсти Уилсон, Зам. председателя', en: 'Kirsty Wilson, Deputy Chair', kk: 'Кирсти Уилсон, вице-төраға' }, photo: P('Кирсти Уилсон.jpg'), sessions: [1,3] },
    { name: 'Citi',           logo: L.Citi, url: 'https://www.citi.com',          full: { ru: 'Citi (Citigroup)', en: 'Citi (Citigroup)', kk: 'Citi (Citigroup)' }, rep: { ru: 'Джули Монако, Управляющий директор', en: 'Julie Monaco, Managing Director', kk: 'Джули Монако, MD' }, photo: null, sessions: [1] },
    { name: 'VISA',           logo: L.Visa, url: 'https://www.visa.com',           full: { ru: 'Visa Inc.', en: 'Visa Inc.', kk: 'Visa Inc.' }, rep: { ru: 'Кристина Дорос, Вице-президент ЦА', en: 'Kristina Doros, VP Central Asia', kk: 'Кристина Дорос, VP ОА' }, photo: null, sessions: [1] },
    { name: 'Microsoft',      logo: L.Microsoft, url: 'https://www.microsoft.com',      full: { ru: 'Microsoft Corporation', en: 'Microsoft Corporation', kk: 'Microsoft Corporation' }, rep: { ru: 'Мишель Симмонс, Президент Microsoft ЦЕ и ЦА', en: 'Michel Simmons, President Microsoft CE & CA', kk: 'Мишель Симмонс, Microsoft президенті' }, photo: P('Мишель Симмонс.jpg'), sessions: [2] },
    { name: 'Air Liquide',    logo: L.AirLiquide, url: 'https://www.airliquide.com',     full: { ru: 'Air Liquide S.A.', en: 'Air Liquide S.A.', kk: 'Air Liquide S.A.' }, rep: { ru: 'Эмили Муран-Ренуар, Вице-президент', en: 'Émilie Mouran-Renouard, Vice President', kk: 'Эмили Муран-Ренуар, VP' }, photo: P('Эмили Муран-Ренуар.png'), sessions: [3] },
    { name: 'VEON',           logo: L.VEON, url: 'https://www.veon.com',           full: { ru: 'VEON Group', en: 'VEON Group', kk: 'VEON Group' }, rep: { ru: 'Марине Бабаян, Вице-президент', en: 'Marine Babayan, VP', kk: 'Марине Бабаян, VP' }, photo: P('Марине Бабаян.jpg'), sessions: [2,3] },
    { name: 'Baker Hughes',   logo: L.BakerHughes, url: 'https://www.bakerhughes.com',    full: { ru: 'Baker Hughes Company', en: 'Baker Hughes Company', kk: 'Baker Hughes Company' }, rep: { ru: 'Мария Клаудия Боррас, Главный управляющий', en: 'Maria Claudia Borras, CEO', kk: 'Мария Клаудия Боррас, CEO' }, photo: null, sessions: [2] },
    { name: 'Polpharma',      logo: L.Polpharma, url: 'https://www.polpharma.com',      full: { ru: 'Polpharma Group', en: 'Polpharma Group', kk: 'Polpharma Group' }, rep: null, photo: null, sessions: [2] },
    { name: 'Chevron',        logo: L.Chevron, url: 'https://www.chevron.com',        full: { ru: 'Chevron Corporation', en: 'Chevron Corporation', kk: 'Chevron Corporation' }, rep: null, photo: null, sessions: [] },
    { name: 'Shell',          logo: L.Shell, url: 'https://www.shell.com',          full: { ru: 'Shell plc', en: 'Shell plc', kk: 'Shell plc' }, rep: null, photo: null, sessions: [] },
    { name: 'ExxonMobil',     logo: L.ExxonMobil, url: 'https://www.exxonmobil.com',     full: { ru: 'ExxonMobil Corporation', en: 'ExxonMobil Corporation', kk: 'ExxonMobil Corporation' }, rep: null, photo: null, sessions: [] },
    { name: 'Alstom',         logo: L.Alstom, url: 'https://www.alstomgroup.com',         full: { ru: 'Alstom S.A.', en: 'Alstom S.A.', kk: 'Alstom S.A.' }, rep: null, photo: null, sessions: [] },
  ],
  natl: [
    { name: 'Нацкомиссия',          logo: L.NacKomissiya, url: 'https://www.akorda.kz', full: { ru: 'Национальная комиссия по делам женщин и семейно-демографической политике при Президенте РК', en: "National Commission on Women's Affairs under the President of Kazakhstan", kk: 'ҚР Президентінің жанындағы Ұлттық комиссия' }, rep: { ru: 'Аида Балаева, Председатель', en: 'Aida Balayeva, Chair', kk: 'Аида Балаева, Төрайым' }, photo: P('Аида Балаева.webp'), sessions: [1] },
    { name: 'Конституционный суд РК',logo: L.KonstSud, url: 'https://ks.gov.kz',    full: { ru: 'Конституционный Суд Республики Казахстан', en: 'Constitutional Court of Kazakhstan', kk: 'ҚР Конституциялық Соты' }, rep: { ru: 'Эльвира Азимова, Председатель', en: 'Elvira Azimova, Chair', kk: 'Эльвира Азимова, Төрайым' }, photo: P('Эльвира Азимова.jpg'), sessions: [1,2] },
    { name: 'Министерство труда РК', logo: L.MinTrud, url: 'https://www.enbek.gov.kz',     full: { ru: 'Министерство труда и социальной защиты населения РК', en: 'Ministry of Labour and Social Protection of Kazakhstan', kk: 'ҚР Еңбек министрлігі' }, rep: { ru: 'Тамара Дуйсенова, Министр', en: 'Tamara Duissenova, Minister', kk: 'Тамара Дуйсенова, министр' }, photo: P('Тамара_Дуйсенова.jpeg'), sessions: [1,2] },
    { name: 'Министерство здравоохранения РК', logo: L.MinZdrav, url: 'https://www.gov.kz/memleket/entities/dsm', full: { ru: 'Министерство здравоохранения РК', en: 'Ministry of Healthcare of Kazakhstan', kk: 'ҚР Денсаулық сақтау министрлігі' }, rep: { ru: 'Акмарал Альназарова, Министр', en: 'Akmaral Alnazarova, Minister', kk: 'Акмарал Альназарова, министр' }, photo: null, sessions: [3] },
    { name: 'Министерство культуры РК', logo: L.MinKultura, url: 'https://www.gov.kz/memleket/entities/mki', full: { ru: 'Министерство культуры и информации РК', en: 'Ministry of Culture and Information of Kazakhstan', kk: 'ҚР Мәдениет министрлігі' }, rep: null, photo: null, sessions: [] },
    { name: 'Мин. цифрового развития РК', logo: L.MinDigital, url: 'https://www.gov.kz/memleket/entities/mdai', full: { ru: 'Министерство цифрового развития, инноваций и аэрокосмической промышленности РК', en: 'Ministry of Digital Development of Kazakhstan', kk: 'ҚР Цифрлық даму министрлігі' }, rep: null, photo: null, sessions: [3] },
    { name: 'Министерство науки РК', logo: L.MinNauka, url: 'https://www.gov.kz/memleket/entities/mns', full: { ru: 'Министерство науки и высшего образования РК', en: 'Ministry of Science and Higher Education of Kazakhstan', kk: 'ҚР Ғылым министрлігі' }, rep: null, photo: null, sessions: [3] },
    { name: 'АРРФР',                logo: L.ARRFR, url: 'https://www.afsa.kz',       full: { ru: 'Агентство РК по регулированию и развитию финансового рынка', en: 'Agency for Regulation and Development of the Financial Market', kk: 'ҚР АРРФР' }, rep: { ru: 'Мадина Абылкасымова, Председатель', en: 'Madina Abylkassymova, Chair', kk: 'Мадина Абылкасымова, Төрайым' }, photo: null, sessions: [1,3] },
    { name: 'Halyk Bank',           logo: L.HalykBank, url: 'https://www.halykbank.kz',   full: { ru: 'АО «Народный Банк Казахстана»', en: 'Halyk Bank Kazakhstan', kk: 'Халық Банкі' }, rep: { ru: 'Умут Шаяхметова, Председатель Правления', en: 'Umut Shayakhmetova, CEO', kk: 'Үмбетова Шаяхметова, Басқарма Төрайымы' }, photo: null, sessions: [1] },
    { name: 'Фонд «Даму»',          logo: L.FondDamu, url: 'https://damu.kz',    full: { ru: 'АО «Фонд развития предпринимательства «Даму»', en: 'Damu Entrepreneurship Development Fund', kk: '«Даму» кәсіпкерлікті дамыту қоры' }, rep: { ru: 'Гаухар Бурибаева, Председатель Правления', en: 'Gauhar Buribayeva, CEO', kk: 'Гаухар Бурибаева, Басқарма Төрайымы' }, photo: null, sessions: [1,2] },
    { name: 'Citibank Kazakhstan',   logo: L.CitibankKZ, url: 'https://www.citi.com/russia/kaz',  full: { ru: 'АО «Ситибанк Казахстан»', en: 'Citibank Kazakhstan', kk: 'Citibank Қазақстан' }, rep: { ru: 'Сауле Жакаева, Председатель Правления', en: 'Saule Zhakayeva, CEO', kk: 'Сауле Жақаева, Басқарма Төрайымы' }, photo: null, sessions: [1] },
    { name: 'AIFC',                 logo: L.AIFC, url: 'https://www.aifc.kz',        full: { ru: 'Международный финансовый центр «Астана»', en: 'Astana International Financial Centre', kk: 'Астана халықаралық қаржы орталығы' }, rep: null, photo: null, sessions: [] },
  ],
  inst: [
    { name: 'Атамекен', logo: L.Atameken, url: 'https://atameken.kz', full: { ru: 'Национальная палата предпринимателей «Атамекен»', en: 'National Chamber of Entrepreneurs «Atameken»', kk: '«Атамекен» ҰКП' }, rep: null, photo: null, sessions: [] },
    { name: 'КазНУИ',  logo: L.KazNUI, url: 'https://kaznui.kz',   full: { ru: 'Казахский национальный университет искусств', en: 'Kazakh National University of Arts', kk: 'Қазақ ұлттық өнер университеті' }, rep: null, photo: null, sessions: [] },
    { name: 'АГУ',     logo: L.AGU, url: 'https://apa.kz',      full: { ru: 'Академия государственного управления при Президенте РК', en: 'Academy of Public Administration under the President of Kazakhstan', kk: 'ҚР Президентінің жанындағы Мемлекеттік басқару академиясы' }, rep: null, photo: null, sessions: [] },
  ],
}

export const STATIC_PARTNERS = PARTNERS
