export const CONTACTS_CONTENT = {
  ru: {
    eyebrow: 'CONTACTS',
    titlePlain: 'Свяжитесь с',
    titleItalic: 'нами',
    subtitle: 'Мы рады партнёрству, заявкам на членство и запросам СМИ',
    infoTitle: 'Контактная информация',
    infoDesc: 'Секретариат GBWC находится в Астане. Открыты для сотрудничества с деловыми женщинами по всему миру.',
    addressLabel: 'АДРЕС', addressVal: 'ул. Достык 16, Talan Towers, Астана',
    phoneLabel: 'ТЕЛЕФОН', phoneVal: '+7 702 731 4400',
    emailLabel: 'EMAIL', emailVal: 'bibigul.maserbaeva@gbwc.network',
    phone2Label: 'ТЕЛЕФОН', phone2Val: '+7 778 124 70 54',
    email2Label: 'EMAIL', email2Val: 'sana.kumargazy@gbwc.network',
    name2: 'Құмарғазы Сана Еркінқызы',
    infoEmail: 'info@gbwc.network',
    socialLabel: 'СОЦИАЛЬНЫЕ СЕТИ',
    formTitle: 'Отправить сообщение',
    fields: { name:'ИМЯ', namePh:'Ваше имя', company:'ОРГАНИЗАЦИЯ', companyPh:'Название организации', email:'EMAIL', emailPh:'email@example.com', subject:'ТЕМА', subjectPh:'Тема сообщения', message:'СООБЩЕНИЕ', messagePh:'Ваше сообщение...' },
    send:'Отправить сообщение', sending:'Отправка…', success:'Спасибо! Сообщение отправлено.', error:'Ошибка. Попробуйте ещё раз.',
  },
  en: {
    eyebrow: 'CONTACTS',
    titlePlain: 'Get in',
    titleItalic: 'touch',
    subtitle: 'We welcome partnerships, membership inquiries, and media requests',
    infoTitle: 'Contact Information',
    infoDesc: 'The GBWC Secretariat is located in Astana. Open to cooperation with businesswomen worldwide.',
    addressLabel: 'ADDRESS', addressVal: '16 Dostyk St., Talan Towers, Astana',
    phoneLabel: 'PHONE', phoneVal: '+7 702 731 4400',
    emailLabel: 'EMAIL', emailVal: 'bibigul.maserbaeva@gbwc.network',
    phone2Label: 'PHONE', phone2Val: '+7 778 124 70 54',
    email2Label: 'EMAIL', email2Val: 'sana.kumargazy@gbwc.network',
    name2: 'Kumargazy Sana Erkinovna',
    infoEmail: 'info@gbwc.network',
    socialLabel: 'SOCIAL',
    formTitle: 'Send a message',
    fields: { name:'NAME', namePh:'Your name', company:'COMPANY', companyPh:'Company name', email:'EMAIL', emailPh:'email@example.com', subject:'SUBJECT', subjectPh:'Select subject', message:'MESSAGE', messagePh:'Your message...' },
    send:'Send Message', sending:'Sending…', success:'Thank you! Your message has been sent.', error:'Failed to send. Please try again.',
  },
  kk: {
    eyebrow: 'БАЙЛАНЫС',
    titlePlain: 'Бізбен',
    titleItalic: 'хабарласыңыз',
    subtitle: 'Серіктестік, мүшелік өтінімдер мен БАҚ сұраулары бойынша ашықпыз',
    infoTitle: 'Байланыс ақпараты',
    infoDesc: 'GBWC Хатшылығы Астанада орналасқан. Бүкіл әлемдегі іскер әйелдермен ынтымақтастыққа ашық.',
    addressLabel: 'МЕКЕНЖАЙ', addressVal: 'Достық к-сі 16, Talan Towers, Астана',
    phoneLabel: 'ТЕЛЕФОН', phoneVal: '+7 702 731 4400',
    emailLabel: 'EMAIL', emailVal: 'bibigul.maserbaeva@gbwc.network',
    phone2Label: 'ТЕЛЕФОН', phone2Val: '+7 778 124 70 54',
    email2Label: 'EMAIL', email2Val: 'sana.kumargazy@gbwc.network',
    name2: 'Құмарғазы Сана Еркінқызы',
    infoEmail: 'info@gbwc.network',
    socialLabel: 'ӘЛЕУМЕТТІК ЖЕЛІЛЕР',
    formTitle: 'Хабарлама жіберу',
    fields: { name:'АТЫ', namePh:'Сіздің атыңыз', company:'ҰЙЫМ', companyPh:'Ұйым атауы', email:'EMAIL', emailPh:'email@example.com', subject:'ТАҚЫРЫП', subjectPh:'Тақырыпты таңдаңыз', message:'ХАБАРЛАМА', messagePh:'Сіздің хабарламаңыз...' },
    send:'Хабарлама жіберу', sending:'Жіберілуде…', success:'Рақмет! Хабарлама жіберілді.', error:'Қате. Қайталап көріңіз.',
  },
}
